apiVersion: v1
kind: Service                    
metadata:
  name: limoneno-backend     
spec:
  type: LoadBalancer                  
  ports:                         
  - port: 5000
    targetPort: 5000
  selector:
    app: limoneno-backend   