name: Build push AWS ECR and deploy to AWS EKS

on:
  push:
    branches: [ "main" ]

jobs:
  
  build-push:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Remplazando variables configmap
        uses: datamonsters/replace-action@v2
        with:
          files: 'eks/api-configmap.yml'
          replacements: 'DB_PASS=${{ secrets.DB_PASS }},DB_NAME=${{ secrets.DB_NAME }},DB_USERNAME=${{ secrets.DB_USERNAME }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},REDISURL=${{ secrets.REDISURL }},SERVER_NAME=${{ secrets.SERVER_NAME }}'
      - name: Remplazando variables mysql-svc
        uses: datamonsters/replace-action@v2
        with:
          files: 'eks/mysql-svc.yml'
          replacements: 'ENDPOINT_MSQL=${{ secrets.ENDPOINT_MSQL }}'      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: limoneno-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --file Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "Replace image in deployment"
          imagen=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          sed -i "s|IMAGE_ECR|${imagen}|" eks/limoneno-backend-deployment.yml
          cat eks/limoneno-backend-deployment.yml      
      - name: Install and configure kubectl
        run: |
          VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
          curl https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl \
          --progress-bar \
          --location \
          --remote-name
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          aws eks --region ${{ secrets.REGION }} update-kubeconfig --name Limoneno 
      - name: Deploy eks
        run: |
          cd eks
          list_deployments=$(kubectl get deployment)
          if [[ "$list_deployments" == *"limoneno-backend"* ]]; then
            kubectl delete deployment limoneno-backend
            kubectl delete services limoneno-backend
            kubectl delete configmap api-config
            kubectl apply -f .
          else
            kubectl apply -f .
          fi

